-------------------------------------------------------------------------------
--
-- File Name : t2d_vme.vhd
--    Author : Y.Iwasaki
--   History : 00 : 2015/04/16 : First version
--
-------------------------------------------------------------------------------
--
-------------------------------------------------------------------------------

library IEEE;
  use   IEEE.std_logic_1164.all;
  use   IEEE.std_logic_unsigned.all;
  use   IEEE.std_logic_arith.all;

use work.VMEA_UT3_map.all;

entity T2D_VME is
generic(
    IGNORE_SOME_IO_TO_SPEEDUP : integer := 0
);
port(
    CLKIN    : in STD_LOGIC;			     
    EN_UI    : in std_logic;
    DOUT_UI  : out std_logic_vector(31 downto 0);
    DIN_UI   : in std_logic_vector(31 downto 0);
    ADDR_UI  : in std_logic_vector(15 downto 2);
    WEN_UI   : in std_logic;
    DTACK_UI : out std_logic;

    VME_READ     : in REG_32x256;
    VME_WRITE    : out REG_32x256
);

end T2D_VME;

-------------------------------------------------------------------------------

architecture RTL of T2D_VME is

begin

    ignore0 : if IGNORE_SOME_IO_TO_SPEEDUP = 0 generate
                                              
    UI_client_T2D : process (CLKIN, EN_UI)
    begin
        if (CLKIN'event and CLKIN = '1') then
            if (EN_UI = '1') then
                -- read operation
                if (WEN_UI = '0') then
                    case ADDR_UI(15 downto 2) is
                        -- For the general registers : 0x1000 - 0xFFFC
                        when ADDR_0 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(0);
                        when ADDR_1 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(1);
                        when ADDR_2 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(2);
                        when ADDR_3 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(3);
                        when ADDR_4 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(4);
                        when ADDR_5 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(5);
                        when ADDR_6 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(6);
                        when ADDR_7 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(7);
                        when ADDR_8 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(8);
                        when ADDR_9 => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(9);
                        when ADDR_a => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(10);
                        when ADDR_b => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(11);
                        when ADDR_c => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(12);
                        when ADDR_d => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(13);
                        when ADDR_e => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(14);
                        when ADDR_f => DTACK_UI <= '1';
                                       DOUT_UI <= VME_READ(15);
                        when ADDR_10 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(16);
                        when ADDR_11 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(17);
                        when ADDR_12 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(18);
                        when ADDR_13 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(19);
                        when ADDR_14 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(20);
                        when ADDR_15 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(21);
                        when ADDR_16 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(22);
                        when ADDR_17 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(23);
                        when ADDR_18 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(24);
                        when ADDR_19 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(25);
                        when ADDR_1a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(26);
                        when ADDR_1b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(27);
                        when ADDR_1c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(28);
                        when ADDR_1d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(29);
                        when ADDR_1e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(30);
                        when ADDR_1f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(31);
                        when ADDR_20 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(32);
                        when ADDR_21 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(33);
                        when ADDR_22 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(34);
                        when ADDR_23 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(35);
                        when ADDR_24 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(36);
                        when ADDR_25 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(37);
                        when ADDR_26 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(38);
                        when ADDR_27 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(39);
                        when ADDR_28 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(40);
                        when ADDR_29 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(41);
                        when ADDR_2a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(42);
                        when ADDR_2b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(43);
                        when ADDR_2c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(44);
                        when ADDR_2d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(45);
                        when ADDR_2e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(46);
                        when ADDR_2f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(47);
                        when ADDR_30 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(48);
                        when ADDR_31 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(49);
                        when ADDR_32 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(50);
                        when ADDR_33 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(51);
                        when ADDR_34 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(52);
                        when ADDR_35 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(53);
                        when ADDR_36 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(54);
                        when ADDR_37 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(55);
                        when ADDR_38 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(56);
                        when ADDR_39 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(57);
                        when ADDR_3a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(58);
                        when ADDR_3b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(59);
                        when ADDR_3c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(60);
                        when ADDR_3d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(61);
                        when ADDR_3e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(62);
                        when ADDR_3f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(63);
                        when ADDR_40 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(64);
                        when ADDR_41 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(65);
                        when ADDR_42 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(66);
                        when ADDR_43 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(67);
                        when ADDR_44 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(68);
                        when ADDR_45 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(69);
                        when ADDR_46 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(70);
                        when ADDR_47 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(71);
                        when ADDR_48 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(72);
                        when ADDR_49 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(73);
                        when ADDR_4a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(74);
                        when ADDR_4b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(75);
                        when ADDR_4c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(76);
                        when ADDR_4d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(77);
                        when ADDR_4e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(78);
                        when ADDR_4f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(79);
                        when ADDR_50 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(80);
                        when ADDR_51 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(81);
                        when ADDR_52 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(82);
                        when ADDR_53 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(83);
                        when ADDR_54 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(84);
                        when ADDR_55 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(85);
                        when ADDR_56 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(86);
                        when ADDR_57 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(87);
                        when ADDR_58 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(88);
                        when ADDR_59 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(89);
                        when ADDR_5a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(90);
                        when ADDR_5b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(91);
                        when ADDR_5c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(92);
                        when ADDR_5d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(93);
                        when ADDR_5e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(94);
                        when ADDR_5f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(95);
                        when ADDR_60 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(96);
                        when ADDR_61 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(97);
                        when ADDR_62 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(98);
                        when ADDR_63 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(99);
                        when ADDR_64 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(100);
                        when ADDR_65 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(101);
                        when ADDR_66 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(102);
                        when ADDR_67 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(103);
                        when ADDR_68 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(104);
                        when ADDR_69 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(105);
                        when ADDR_6a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(106);
                        when ADDR_6b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(107);
                        when ADDR_6c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(108);
                        when ADDR_6d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(109);
                        when ADDR_6e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(110);
                        when ADDR_6f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(111);
                        when ADDR_70 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(112);
                        when ADDR_71 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(113);
                        when ADDR_72 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(114);
                        when ADDR_73 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(115);
                        when ADDR_74 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(116);
                        when ADDR_75 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(117);
                        when ADDR_76 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(118);
                        when ADDR_77 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(119);
                        when ADDR_78 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(120);
                        when ADDR_79 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(121);
                        when ADDR_7a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(122);
                        when ADDR_7b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(123);
                        when ADDR_7c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(124);
                        when ADDR_7d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(125);
                        when ADDR_7e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(126);
                        when ADDR_7f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(127);
                        when ADDR_80 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(128);
                        when ADDR_81 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(129);
                        when ADDR_82 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(130);
                        when ADDR_83 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(131);
                        when ADDR_84 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(132);
                        when ADDR_85 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(133);
                        when ADDR_86 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(134);
                        when ADDR_87 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(135);
                        when ADDR_88 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(136);
                        when ADDR_89 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(137);
                        when ADDR_8a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(138);
                        when ADDR_8b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(139);
                        when ADDR_8c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(140);
                        when ADDR_8d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(141);
                        when ADDR_8e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(142);
                        when ADDR_8f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(143);
                        when ADDR_90 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(144);
                        when ADDR_91 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(145);
                        when ADDR_92 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(146);
                        when ADDR_93 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(147);
                        when ADDR_94 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(148);
                        when ADDR_95 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(149);
                        when ADDR_96 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(150);
                        when ADDR_97 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(151);
                        when ADDR_98 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(152);
                        when ADDR_99 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(153);
                        when ADDR_9a => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(154);
                        when ADDR_9b => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(155);
                        when ADDR_9c => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(156);
                        when ADDR_9d => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(157);
                        when ADDR_9e => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(158);
                        when ADDR_9f => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(159);
                        when ADDR_a0 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(160);
                        when ADDR_a1 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(161);
                        when ADDR_a2 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(162);
                        when ADDR_a3 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(163);
                        when ADDR_a4 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(164);
                        when ADDR_a5 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(165);
                        when ADDR_a6 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(166);
                        when ADDR_a7 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(167);
                        when ADDR_a8 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(168);
                        when ADDR_a9 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(169);
                        when ADDR_aa => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(170);
                        when ADDR_ab => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(171);
                        when ADDR_ac => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(172);
                        when ADDR_ad => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(173);
                        when ADDR_ae => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(174);
                        when ADDR_af => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(175);
                        when ADDR_b0 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(176);
                        when ADDR_b1 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(177);
                        when ADDR_b2 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(178);
                        when ADDR_b3 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(179);
                        when ADDR_b4 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(180);
                        when ADDR_b5 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(181);
                        when ADDR_b6 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(182);
                        when ADDR_b7 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(183);
                        when ADDR_b8 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(184);
                        when ADDR_b9 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(185);
                        when ADDR_ba => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(186);
                        when ADDR_bb => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(187);
                        when ADDR_bc => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(188);
                        when ADDR_bd => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(189);
                        when ADDR_be => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(190);
                        when ADDR_bf => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(191);
                        when ADDR_c0 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(192);
                        when ADDR_c1 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(193);
                        when ADDR_c2 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(194);
                        when ADDR_c3 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(195);
                        when ADDR_c4 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(196);
                        when ADDR_c5 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(197);
                        when ADDR_c6 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(198);
                        when ADDR_c7 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(199);
                        when ADDR_c8 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(200);
                        when ADDR_c9 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(201);
                        when ADDR_ca => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(202);
                        when ADDR_cb => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(203);
                        when ADDR_cc => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(204);
                        when ADDR_cd => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(205);
                        when ADDR_ce => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(206);
                        when ADDR_cf => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(207);
                        when ADDR_d0 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(208);
                        when ADDR_d1 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(209);
                        when ADDR_d2 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(210);
                        when ADDR_d3 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(211);
                        when ADDR_d4 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(212);
                        when ADDR_d5 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(213);
                        when ADDR_d6 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(214);
                        when ADDR_d7 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(215);
                        when ADDR_d8 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(216);
                        when ADDR_d9 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(217);
                        when ADDR_da => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(218);
                        when ADDR_db => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(219);
                        when ADDR_dc => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(220);
                        when ADDR_dd => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(221);
                        when ADDR_de => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(222);
                        when ADDR_df => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(223);
                        when ADDR_e0 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(224);
                        when ADDR_e1 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(225);
                        when ADDR_e2 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(226);
                        when ADDR_e3 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(227);
                        when ADDR_e4 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(228);
                        when ADDR_e5 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(229);
                        when ADDR_e6 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(230);
                        when ADDR_e7 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(231);
                        when ADDR_e8 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(232);
                        when ADDR_e9 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(233);
                        when ADDR_ea => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(234);
                        when ADDR_eb => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(235);
                        when ADDR_ec => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(236);
                        when ADDR_ed => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(237);
                        when ADDR_ee => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(238);
                        when ADDR_ef => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(239);
                        when ADDR_f0 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(240);
                        when ADDR_f1 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(241);
                        when ADDR_f2 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(242);
                        when ADDR_f3 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(243);
                        when ADDR_f4 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(244);
                        when ADDR_f5 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(245);
                        when ADDR_f6 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(246);
                        when ADDR_f7 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(247);
                        when ADDR_f8 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(248);
                        when ADDR_f9 => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(249);
                        when ADDR_fa => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(250);
                        when ADDR_fb => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(251);
                        when ADDR_fc => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(252);
                        when ADDR_fd => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(253);
                        when ADDR_fe => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(254);
                        when ADDR_ff => DTACK_UI <= '1';
                                        DOUT_UI <= VME_READ(255);
                        when others => DTACK_UI <= '0';
                                       DOUT_UI <= (others=> '0');
                    end case;

                -- write operation
                elsif (WEN_UI = '1') then
                    DOUT_UI <= (others=> '0');
                    case ADDR_UI(15 downto 2) is
                        -- For the general registers : 0x1000 - 0xFFFC
                        when ADDR_0 => VME_WRITE(0) <= DIN_UI;
                        when ADDR_1 => VME_WRITE(1) <= DIN_UI;
                        when ADDR_2 => VME_WRITE(2) <= DIN_UI;
                        when ADDR_3 => VME_WRITE(3) <= DIN_UI;
                        when ADDR_4 => VME_WRITE(4) <= DIN_UI;
                        when ADDR_5 => VME_WRITE(5) <= DIN_UI;
                        when ADDR_6 => VME_WRITE(6) <= DIN_UI;
                        when ADDR_7 => VME_WRITE(7) <= DIN_UI;
                        when ADDR_8 => VME_WRITE(8) <= DIN_UI;
                        when ADDR_9 => VME_WRITE(9) <= DIN_UI;
                        when ADDR_a => VME_WRITE(10) <= DIN_UI;
                        when ADDR_b => VME_WRITE(11) <= DIN_UI;
                        when ADDR_c => VME_WRITE(12) <= DIN_UI;
                        when ADDR_d => VME_WRITE(13) <= DIN_UI;
                        when ADDR_e => VME_WRITE(14) <= DIN_UI;
                        when ADDR_f => VME_WRITE(15) <= DIN_UI;
                        when ADDR_10 => VME_WRITE(16) <= DIN_UI;
                        when ADDR_11 => VME_WRITE(17) <= DIN_UI;
                        when ADDR_12 => VME_WRITE(18) <= DIN_UI;
                        when ADDR_13 => VME_WRITE(19) <= DIN_UI;
                        when ADDR_14 => VME_WRITE(20) <= DIN_UI;
                        when ADDR_15 => VME_WRITE(21) <= DIN_UI;
                        when ADDR_16 => VME_WRITE(22) <= DIN_UI;
                        when ADDR_17 => VME_WRITE(23) <= DIN_UI;
                        when ADDR_18 => VME_WRITE(24) <= DIN_UI;
                        when ADDR_19 => VME_WRITE(25) <= DIN_UI;
                        when ADDR_1a => VME_WRITE(26) <= DIN_UI;
                        when ADDR_1b => VME_WRITE(27) <= DIN_UI;
                        when ADDR_1c => VME_WRITE(28) <= DIN_UI;
                        when ADDR_1d => VME_WRITE(29) <= DIN_UI;
                        when ADDR_1e => VME_WRITE(30) <= DIN_UI;
                        when ADDR_1f => VME_WRITE(31) <= DIN_UI;
                        when ADDR_20 => VME_WRITE(32) <= DIN_UI;
                        when ADDR_21 => VME_WRITE(33) <= DIN_UI;
                        when ADDR_22 => VME_WRITE(34) <= DIN_UI;
                        when ADDR_23 => VME_WRITE(35) <= DIN_UI;
                        when ADDR_24 => VME_WRITE(36) <= DIN_UI;
                        when ADDR_25 => VME_WRITE(37) <= DIN_UI;
                        when ADDR_26 => VME_WRITE(38) <= DIN_UI;
                        when ADDR_27 => VME_WRITE(39) <= DIN_UI;
                        when ADDR_28 => VME_WRITE(40) <= DIN_UI;
                        when ADDR_29 => VME_WRITE(41) <= DIN_UI;
                        when ADDR_2a => VME_WRITE(42) <= DIN_UI;
                        when ADDR_2b => VME_WRITE(43) <= DIN_UI;
                        when ADDR_2c => VME_WRITE(44) <= DIN_UI;
                        when ADDR_2d => VME_WRITE(45) <= DIN_UI;
                        when ADDR_2e => VME_WRITE(46) <= DIN_UI;
                        when ADDR_2f => VME_WRITE(47) <= DIN_UI;
                        when ADDR_30 => VME_WRITE(48) <= DIN_UI;
                        when ADDR_31 => VME_WRITE(49) <= DIN_UI;
                        when ADDR_32 => VME_WRITE(50) <= DIN_UI;
                        when ADDR_33 => VME_WRITE(51) <= DIN_UI;
                        when ADDR_34 => VME_WRITE(52) <= DIN_UI;
                        when ADDR_35 => VME_WRITE(53) <= DIN_UI;
                        when ADDR_36 => VME_WRITE(54) <= DIN_UI;
                        when ADDR_37 => VME_WRITE(55) <= DIN_UI;
                        when ADDR_38 => VME_WRITE(56) <= DIN_UI;
                        when ADDR_39 => VME_WRITE(57) <= DIN_UI;
                        when ADDR_3a => VME_WRITE(58) <= DIN_UI;
                        when ADDR_3b => VME_WRITE(59) <= DIN_UI;
                        when ADDR_3c => VME_WRITE(60) <= DIN_UI;
                        when ADDR_3d => VME_WRITE(61) <= DIN_UI;
                        when ADDR_3e => VME_WRITE(62) <= DIN_UI;
                        when ADDR_3f => VME_WRITE(63) <= DIN_UI;
                        when ADDR_40 => VME_WRITE(64) <= DIN_UI;
                        when ADDR_41 => VME_WRITE(65) <= DIN_UI;
                        when ADDR_42 => VME_WRITE(66) <= DIN_UI;
                        when ADDR_43 => VME_WRITE(67) <= DIN_UI;
                        when ADDR_44 => VME_WRITE(68) <= DIN_UI;
                        when ADDR_45 => VME_WRITE(69) <= DIN_UI;
                        when ADDR_46 => VME_WRITE(70) <= DIN_UI;
                        when ADDR_47 => VME_WRITE(71) <= DIN_UI;
                        when ADDR_48 => VME_WRITE(72) <= DIN_UI;
                        when ADDR_49 => VME_WRITE(73) <= DIN_UI;
                        when ADDR_4a => VME_WRITE(74) <= DIN_UI;
                        when ADDR_4b => VME_WRITE(75) <= DIN_UI;
                        when ADDR_4c => VME_WRITE(76) <= DIN_UI;
                        when ADDR_4d => VME_WRITE(77) <= DIN_UI;
                        when ADDR_4e => VME_WRITE(78) <= DIN_UI;
                        when ADDR_4f => VME_WRITE(79) <= DIN_UI;
                        when ADDR_50 => VME_WRITE(80) <= DIN_UI;
                        when ADDR_51 => VME_WRITE(81) <= DIN_UI;
                        when ADDR_52 => VME_WRITE(82) <= DIN_UI;
                        when ADDR_53 => VME_WRITE(83) <= DIN_UI;
                        when ADDR_54 => VME_WRITE(84) <= DIN_UI;
                        when ADDR_55 => VME_WRITE(85) <= DIN_UI;
                        when ADDR_56 => VME_WRITE(86) <= DIN_UI;
                        when ADDR_57 => VME_WRITE(87) <= DIN_UI;
                        when ADDR_58 => VME_WRITE(88) <= DIN_UI;
                        when ADDR_59 => VME_WRITE(89) <= DIN_UI;
                        when ADDR_5a => VME_WRITE(90) <= DIN_UI;
                        when ADDR_5b => VME_WRITE(91) <= DIN_UI;
                        when ADDR_5c => VME_WRITE(92) <= DIN_UI;
                        when ADDR_5d => VME_WRITE(93) <= DIN_UI;
                        when ADDR_5e => VME_WRITE(94) <= DIN_UI;
                        when ADDR_5f => VME_WRITE(95) <= DIN_UI;
                        when ADDR_60 => VME_WRITE(96) <= DIN_UI;
                        when ADDR_61 => VME_WRITE(97) <= DIN_UI;
                        when ADDR_62 => VME_WRITE(98) <= DIN_UI;
                        when ADDR_63 => VME_WRITE(99) <= DIN_UI;
                        when ADDR_64 => VME_WRITE(100) <= DIN_UI;
                        when ADDR_65 => VME_WRITE(101) <= DIN_UI;
                        when ADDR_66 => VME_WRITE(102) <= DIN_UI;
                        when ADDR_67 => VME_WRITE(103) <= DIN_UI;
                        when ADDR_68 => VME_WRITE(104) <= DIN_UI;
                        when ADDR_69 => VME_WRITE(105) <= DIN_UI;
                        when ADDR_6a => VME_WRITE(106) <= DIN_UI;
                        when ADDR_6b => VME_WRITE(107) <= DIN_UI;
                        when ADDR_6c => VME_WRITE(108) <= DIN_UI;
                        when ADDR_6d => VME_WRITE(109) <= DIN_UI;
                        when ADDR_6e => VME_WRITE(110) <= DIN_UI;
                        when ADDR_6f => VME_WRITE(111) <= DIN_UI;
                        when ADDR_70 => VME_WRITE(112) <= DIN_UI;
                        when ADDR_71 => VME_WRITE(113) <= DIN_UI;
                        when ADDR_72 => VME_WRITE(114) <= DIN_UI;
                        when ADDR_73 => VME_WRITE(115) <= DIN_UI;
                        when ADDR_74 => VME_WRITE(116) <= DIN_UI;
                        when ADDR_75 => VME_WRITE(117) <= DIN_UI;
                        when ADDR_76 => VME_WRITE(118) <= DIN_UI;
                        when ADDR_77 => VME_WRITE(119) <= DIN_UI;
                        when ADDR_78 => VME_WRITE(120) <= DIN_UI;
                        when ADDR_79 => VME_WRITE(121) <= DIN_UI;
                        when ADDR_7a => VME_WRITE(122) <= DIN_UI;
                        when ADDR_7b => VME_WRITE(123) <= DIN_UI;
                        when ADDR_7c => VME_WRITE(124) <= DIN_UI;
                        when ADDR_7d => VME_WRITE(125) <= DIN_UI;
                        when ADDR_7e => VME_WRITE(126) <= DIN_UI;
                        when ADDR_7f => VME_WRITE(127) <= DIN_UI;
                        when ADDR_80 => VME_WRITE(128) <= DIN_UI;
                        when ADDR_81 => VME_WRITE(129) <= DIN_UI;
                        when ADDR_82 => VME_WRITE(130) <= DIN_UI;
                        when ADDR_83 => VME_WRITE(131) <= DIN_UI;
                        when ADDR_84 => VME_WRITE(132) <= DIN_UI;
                        when ADDR_85 => VME_WRITE(133) <= DIN_UI;
                        when ADDR_86 => VME_WRITE(134) <= DIN_UI;
                        when ADDR_87 => VME_WRITE(135) <= DIN_UI;
                        when ADDR_88 => VME_WRITE(136) <= DIN_UI;
                        when ADDR_89 => VME_WRITE(137) <= DIN_UI;
                        when ADDR_8a => VME_WRITE(138) <= DIN_UI;
                        when ADDR_8b => VME_WRITE(139) <= DIN_UI;
                        when ADDR_8c => VME_WRITE(140) <= DIN_UI;
                        when ADDR_8d => VME_WRITE(141) <= DIN_UI;
                        when ADDR_8e => VME_WRITE(142) <= DIN_UI;
                        when ADDR_8f => VME_WRITE(143) <= DIN_UI;
                        when ADDR_90 => VME_WRITE(144) <= DIN_UI;
                        when ADDR_91 => VME_WRITE(145) <= DIN_UI;
                        when ADDR_92 => VME_WRITE(146) <= DIN_UI;
                        when ADDR_93 => VME_WRITE(147) <= DIN_UI;
                        when ADDR_94 => VME_WRITE(148) <= DIN_UI;
                        when ADDR_95 => VME_WRITE(149) <= DIN_UI;
                        when ADDR_96 => VME_WRITE(150) <= DIN_UI;
                        when ADDR_97 => VME_WRITE(151) <= DIN_UI;
                        when ADDR_98 => VME_WRITE(152) <= DIN_UI;
                        when ADDR_99 => VME_WRITE(153) <= DIN_UI;
                        when ADDR_9a => VME_WRITE(154) <= DIN_UI;
                        when ADDR_9b => VME_WRITE(155) <= DIN_UI;
                        when ADDR_9c => VME_WRITE(156) <= DIN_UI;
                        when ADDR_9d => VME_WRITE(157) <= DIN_UI;
                        when ADDR_9e => VME_WRITE(158) <= DIN_UI;
                        when ADDR_9f => VME_WRITE(159) <= DIN_UI;
                        when ADDR_a0 => VME_WRITE(160) <= DIN_UI;
                        when ADDR_a1 => VME_WRITE(161) <= DIN_UI;
                        when ADDR_a2 => VME_WRITE(162) <= DIN_UI;
                        when ADDR_a3 => VME_WRITE(163) <= DIN_UI;
                        when ADDR_a4 => VME_WRITE(164) <= DIN_UI;
                        when ADDR_a5 => VME_WRITE(165) <= DIN_UI;
                        when ADDR_a6 => VME_WRITE(166) <= DIN_UI;
                        when ADDR_a7 => VME_WRITE(167) <= DIN_UI;
                        when ADDR_a8 => VME_WRITE(168) <= DIN_UI;
                        when ADDR_a9 => VME_WRITE(169) <= DIN_UI;
                        when ADDR_aa => VME_WRITE(170) <= DIN_UI;
                        when ADDR_ab => VME_WRITE(171) <= DIN_UI;
                        when ADDR_ac => VME_WRITE(172) <= DIN_UI;
                        when ADDR_ad => VME_WRITE(173) <= DIN_UI;
                        when ADDR_ae => VME_WRITE(174) <= DIN_UI;
                        when ADDR_af => VME_WRITE(175) <= DIN_UI;
                        when ADDR_b0 => VME_WRITE(176) <= DIN_UI;
                        when ADDR_b1 => VME_WRITE(177) <= DIN_UI;
                        when ADDR_b2 => VME_WRITE(178) <= DIN_UI;
                        when ADDR_b3 => VME_WRITE(179) <= DIN_UI;
                        when ADDR_b4 => VME_WRITE(180) <= DIN_UI;
                        when ADDR_b5 => VME_WRITE(181) <= DIN_UI;
                        when ADDR_b6 => VME_WRITE(182) <= DIN_UI;
                        when ADDR_b7 => VME_WRITE(183) <= DIN_UI;
                        when ADDR_b8 => VME_WRITE(184) <= DIN_UI;
                        when ADDR_b9 => VME_WRITE(185) <= DIN_UI;
                        when ADDR_ba => VME_WRITE(186) <= DIN_UI;
                        when ADDR_bb => VME_WRITE(187) <= DIN_UI;
                        when ADDR_bc => VME_WRITE(188) <= DIN_UI;
                        when ADDR_bd => VME_WRITE(189) <= DIN_UI;
                        when ADDR_be => VME_WRITE(190) <= DIN_UI;
                        when ADDR_bf => VME_WRITE(191) <= DIN_UI;
                        when ADDR_c0 => VME_WRITE(192) <= DIN_UI;
                        when ADDR_c1 => VME_WRITE(193) <= DIN_UI;
                        when ADDR_c2 => VME_WRITE(194) <= DIN_UI;
                        when ADDR_c3 => VME_WRITE(195) <= DIN_UI;
                        when ADDR_c4 => VME_WRITE(196) <= DIN_UI;
                        when ADDR_c5 => VME_WRITE(197) <= DIN_UI;
                        when ADDR_c6 => VME_WRITE(198) <= DIN_UI;
                        when ADDR_c7 => VME_WRITE(199) <= DIN_UI;
                        when ADDR_c8 => VME_WRITE(200) <= DIN_UI;
                        when ADDR_c9 => VME_WRITE(201) <= DIN_UI;
                        when ADDR_ca => VME_WRITE(202) <= DIN_UI;
                        when ADDR_cb => VME_WRITE(203) <= DIN_UI;
                        when ADDR_cc => VME_WRITE(204) <= DIN_UI;
                        when ADDR_cd => VME_WRITE(205) <= DIN_UI;
                        when ADDR_ce => VME_WRITE(206) <= DIN_UI;
                        when ADDR_cf => VME_WRITE(207) <= DIN_UI;
                        when ADDR_d0 => VME_WRITE(208) <= DIN_UI;
                        when ADDR_d1 => VME_WRITE(209) <= DIN_UI;
                        when ADDR_d2 => VME_WRITE(210) <= DIN_UI;
                        when ADDR_d3 => VME_WRITE(211) <= DIN_UI;
                        when ADDR_d4 => VME_WRITE(212) <= DIN_UI;
                        when ADDR_d5 => VME_WRITE(213) <= DIN_UI;
                        when ADDR_d6 => VME_WRITE(214) <= DIN_UI;
                        when ADDR_d7 => VME_WRITE(215) <= DIN_UI;
                        when ADDR_d8 => VME_WRITE(216) <= DIN_UI;
                        when ADDR_d9 => VME_WRITE(217) <= DIN_UI;
                        when ADDR_da => VME_WRITE(218) <= DIN_UI;
                        when ADDR_db => VME_WRITE(219) <= DIN_UI;
                        when ADDR_dc => VME_WRITE(220) <= DIN_UI;
                        when ADDR_dd => VME_WRITE(221) <= DIN_UI;
                        when ADDR_de => VME_WRITE(222) <= DIN_UI;
                        when ADDR_df => VME_WRITE(223) <= DIN_UI;
                        when ADDR_e0 => VME_WRITE(224) <= DIN_UI;
                        when ADDR_e1 => VME_WRITE(225) <= DIN_UI;
                        when ADDR_e2 => VME_WRITE(226) <= DIN_UI;
                        when ADDR_e3 => VME_WRITE(227) <= DIN_UI;
                        when ADDR_e4 => VME_WRITE(228) <= DIN_UI;
                        when ADDR_e5 => VME_WRITE(229) <= DIN_UI;
                        when ADDR_e6 => VME_WRITE(230) <= DIN_UI;
                        when ADDR_e7 => VME_WRITE(231) <= DIN_UI;
                        when ADDR_e8 => VME_WRITE(232) <= DIN_UI;
                        when ADDR_e9 => VME_WRITE(233) <= DIN_UI;
                        when ADDR_ea => VME_WRITE(234) <= DIN_UI;
                        when ADDR_eb => VME_WRITE(235) <= DIN_UI;
                        when ADDR_ec => VME_WRITE(236) <= DIN_UI;
                        when ADDR_ed => VME_WRITE(237) <= DIN_UI;
                        when ADDR_ee => VME_WRITE(238) <= DIN_UI;
                        when ADDR_ef => VME_WRITE(239) <= DIN_UI;
                        when ADDR_f0 => VME_WRITE(240) <= DIN_UI;
                        when ADDR_f1 => VME_WRITE(241) <= DIN_UI;
                        when ADDR_f2 => VME_WRITE(242) <= DIN_UI;
                        when ADDR_f3 => VME_WRITE(243) <= DIN_UI;
                        when ADDR_f4 => VME_WRITE(244) <= DIN_UI;
                        when ADDR_f5 => VME_WRITE(245) <= DIN_UI;
                        when ADDR_f6 => VME_WRITE(246) <= DIN_UI;
                        when ADDR_f7 => VME_WRITE(247) <= DIN_UI;
                        when ADDR_f8 => VME_WRITE(248) <= DIN_UI;
                        when ADDR_f9 => VME_WRITE(249) <= DIN_UI;
                        when ADDR_fa => VME_WRITE(250) <= DIN_UI;
                        when ADDR_fb => VME_WRITE(251) <= DIN_UI;
                        when ADDR_fc => VME_WRITE(252) <= DIN_UI;
                        when ADDR_fd => VME_WRITE(253) <= DIN_UI;
                        when ADDR_fe => VME_WRITE(254) <= DIN_UI;
                        when ADDR_ff => VME_WRITE(255) <= DIN_UI;
                        when others => null;
                    end case;
                end if;
            else
                DTACK_UI <= '0';
            end if;
        end if;
    end process;
    
    end generate ignore0;

end RTL;
